apiVersion: v1
kind: Secret
metadata:
  name: omniai-backend-secrets
  namespace: omniai
type: Opaque
stringData:
  SECRET_KEY: REPLACE_ME
  OPENAI_COMPAT_API_KEY: REPLACE_ME
  NGROK_AUTHTOKEN: REPLACE_ME
