apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omniai-staging

resources:
  - ../../base
  - ingress.yaml

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: omniai/backend
    newTag: "staging-latest"

patches:
  - target:
      kind: Deployment
      name: omniai-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: staging-omniai-config
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: staging-omniai-secrets
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: staging-omniai-data
      - op: replace
        path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
        value: staging-omniai-logs
